spring:
  application:
    name: itokenx-zuul
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      url: http://localhost:8084
# 监控信息显示
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["health","info"]

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  路径管理
zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: itokenx-web-admin-ribbon

    api-b:
      path: /api/b/**
      serviceId: itokenx-web-admin-feign